language: php
dist: xenial
sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - SIMPLETEST_DB=sqlite://tmp/site.sqlite
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"
  matrix:
    - RELEASE=dev COMPOSER_CHANNEL=stable

addons:
  apt:
    packages:
      - sqlite3
      - php-sqlite3

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

install:
  - composer --verbose install

script:
  # Remove symfony/routing once https://www.drupal.org/node/2882456 is fixed
  # @see https://www.drupal.org/node/2887000
  # @see https://www.drupal.org/node/2874909
  - if [[ $RELEASE = dev ]]; then composer --verbose require --no-update symfony/event-dispatcher:~3.2.9 symfony/routing:~3.2.9; fi;
  - if [[ $RELEASE = dev ]]; then composer --verbose update; fi;
  - cd $TRAVIS_BUILD_DIR/web
  - ./../bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite
  - ./../bin/drush runserver $SIMPLETEST_BASE_URL &
  - until curl -s $SIMPLETEST_BASE_URL; do true; done > /dev/null
  # Skip core/tests/Drupal/Tests/ComposerIntegrationTest.php because web/ has no composer.json
  # Ignore PageCache group temporarily, @see https://www.drupal.org/node/2770673
  - ./../bin/phpunit -c core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache
  - ./../bin/drush
